### ISSUE TITLE
not working in V11

### ISSUE THREAD

**Issue by arkhayne** [zarmstrong/hlo-importer#23]
nothing happen when i import a character in V 11

HLO Importer | PF2e System Version: hlo-importer actor type: character
hlo-importer.min.js:1 HLO Importer | Can user modify: true
hlo-importer.min.js:1 HLO Importer | hlo-importer token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIxNDc0ODM2NDcsImhsbyI6IlgtUmc5SU5sc24zemVyQ1NGUG55Qk5SX1NOQTNUOFI5VjJJRlI0c1JHSEdxUGdUSkltVXpyTmFDSnJvTExxTSJ9.IDW6V6KvB4Nr4Yql3E3hJNU8CkTpLRbSUt1ePjqIjSE
hlo-importer.min.js:1 HLO Importer | PF2e System Version: hlo-importer actor type: character
hlo-importer.min.js:1 HLO Importer | Can user modify: true
foundry.js:7602 Foundry VTT | Retrieved and compiled template systems/pf2e/templates/actors/character/manage-tabs.hbs
foundry.js:7602 Foundry VTT | Retrieved and compiled template modules/pf2e-hero-actions/templates/sheet.hbs
foundry.js:7602 Foundry VTT | Retrieved and compiled template modules/pf2e-spells-summary/templates/sheet.hbs
foundry.js:7602 Foundry VTT | Retrieved and compiled template systems/pf2e/templates/actors/character/manage-tabs.hbs
foundry.js:7602 Foundry VTT | Retrieved and compiled template modules/pf2e-hero-actions/templates/sheet.hbs
foundry.js:7602 Foundry VTT | Retrieved and compiled template modules/pf2e-spells-summary/templates/sheet.hbs
foundry.js:5724 Foundry VTT | Rendering ModuleManagement
foundry.js:5724 Foundry VTT | Rendering Dialog
foundry.js:7602 Foundry VTT | Retrieved and compiled template templates/hud/dialog.html
hlo-importer.min.js:51 HLO Importer | usertoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIxNDc0ODM2NDcsImhsbyI6IlgtUmc5SU5sc24zemVyQ1NGUG55Qk5SX1NOQTNUOFI5VjJJRlI0c1JHSEdxUGdUSkltVXpyTmFDSnJvTExxTSJ9.IDW6V6KvB4Nr4Yql3E3hJNU8CkTpLRbSUt1ePjqIjSE
hlo-importer.min.js:51 HLO Importer | PF2e System Version: 5.3.1
hlo-importer.min.js:47 HLO Importer | [object Object]
hlo-importer.min.js:47 Uncaught TypeError: undefined. Cannot convert undefined or null to object
[Detected 1 package: hlo-importer]
    at Function.keys (<anonymous>)
    at xmlhttp.onreadystatechange (hlo-importer.min.js:47:1157)

**Comment by computerpro82** [comment]
I am having similar issues where trying to import from HLO simply hangs without any feedback
Foundry VTT | Rendering Dialog
hlo-importer.min.js:51 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at xmlhttp.onreadystatechange (hlo-importer.min.js:51:131)
xmlhttp.onreadystatechange @ hlo-importer.min.js:51
XMLHttpRequest.send (async)
convertHLOCharacter @ hlo-importer.min.js:51
close @ hlo-importer.min.js:47
close @ foundry.js:65049
submit @ foundry.js:65038
_onClickButton @ foundry.js:64965
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
